### ISSUE TITLE
Broken Link - Design Patterns

### ISSUE THREAD

**Issue by LonelyCat124** [StanfordLegion/StanfordLegion.github.io#2]
The https://legion.stanford.edu/design_patterns/ page linked to from the Documentation page throws a 404 error for me at the moment.

**Comment by LonelyCat124** [comment]
As does the glossary link

**Comment by elliottslaughter** [comment]
We removed these from the website since we never actually populated these pages, and they were taking a long time to build. We should probably just unlink them.

**Comment by elliottslaughter** [comment]
Should be removed now.
